"""Document type configurations for the review pipeline.

Each document type defines its own:
- chapter_keywords: keywords for chapter boundary detection
- entity_patterns: regex patterns for entity extraction
- fact_tool_schema: JSON Schema for the LLM fact-labeling tool
- fact_tool_handler: callable that handles fact-labeling tool calls
- risk_rules: dict of review rules
- rule_keyword_map: mapping from rule IDs to keywords for complexity classification
- simple_rule_ids / complex_rule_ids: rule ID sets for fast vs deep review
- prompt_templates: paths to prompt template files per stage
"""

from pathlib import Path

from app.agents.lpa.risk_rules import LPA_RULES
from app.agents.rules.articles_of_association_rules import ARTICLES_OF_ASSOCIATION_RULES
from app.agents.rules.construction_rules import CONSTRUCTION_RULES
from app.agents.rules.contract_rules import CONTRACT_RULES
from app.agents.rules.employment_rules import EMPLOYMENT_RULES
from app.agents.rules.equity_investment_rules import EQUITY_INVESTMENT_RULES
from app.agents.rules.ip_license_rules import IP_LICENSE_RULES
from app.agents.rules.lease_rules import LEASE_RULES
from app.agents.rules.loan_rules import LOAN_RULES
from app.agents.rules.marital_property_rules import MARITAL_PROPERTY_RULES
from app.agents.rules.nda_rules import NDA_RULES
from app.agents.rules.sales_rules import SALES_RULES
from app.agents.rules.service_rules import SERVICE_RULES
from app.agents.rules.will_estate_rules import WILL_ESTATE_RULES

PROMPTS_DIR = Path(__file__).resolve().parent.parent.parent.parent / "prompts"

# LPA chapter keywords (Chinese/English bilingual)
_LPA_CHAPTER_KEYWORDS = [
    "定义",
    "definitions",
    "interpretation",
    "释义",
    "出资",
    "capital contribution",
    "capital commitment",
    "认缴",
    "管理费",
    "management fee",
    "报酬",
    "分配",
    "distribution",
    "allocation",
    "waterfall",
    "投资",
    "investment",
    "investments",
    "普通合伙人",
    "general partner",
    "有限合伙人",
    "limited partner",
    "合伙人会议",
    "咨询委员会",
    "advisory committee",
    "lpac",
    "转让",
    "transfer",
    "退伙",
    "withdrawal",
    "解散",
    "清算",
    "dissolution",
    "liquidation",
    "违约责任",
    "default",
    "争议解决",
    "dispute resolution",
    "其他",
    "miscellaneous",
    "签署",
    "signature",
    "execution",
]

# LPA entity patterns
_LPA_ENTITY_PATTERNS = [
    r"(?:甲方|乙方|丙方|普通合伙人|有限合伙人|基金管理人|执行事务合伙人|GP|LP|管理人)[：:\s]*([^\n,，。；;]+?(?:公司|企业|基金|合伙|Co\.|Ltd\.|LLP|Inc\.|Corp\.))",
]

# LPA rule-to-keyword mapping for chapter complexity classification
_LPA_RULE_KEYWORD_MAP = {
    "B1": ["管理费", "management fee", "报酬"],
    "B2": ["管理费", "management fee", "基数", "basis"],
    "B3": ["管理费", "management fee", "step-down", "减免"],
    "B4": ["费用", "expense", "分担", "allocation"],
    "B5": ["关联方", "related party", "费用"],
    "C1": ["分配", "distribution", "waterfall", "瀑布"],
    "C2": ["优先回报", "preferred return", "hurdle"],
    "C3": ["carry", "业绩报酬", "超额收益"],
    "C4": ["回拨", "clawback"],
    "C5": ["跟投", "co-investment"],
    "D1": ["关键人士", "key man", "key person"],
    "D2": ["除名", "removal", "罢免"],
    "D3": ["关联交易", "related party transaction"],
    "D4": ["投资限制", "investment restriction"],
    "D5": ["转让", "transfer", "退伙", "withdrawal"],
    "D7": ["风险管理", "risk management"],
    "E1": ["集中度", "concentration"],
    "E2": ["跟投", "co-investment"],
    "E3": ["后续投资", "follow-on"],
    "E4": ["杠杆", "leverage"],
}

# LPA simple/complex rule IDs
_LPA_SIMPLE_RULE_IDS = {"A1", "A2", "A3", "A4", "A5", "D6", "D8"}
_LPA_COMPLEX_RULE_IDS = {
    "B1",
    "B2",
    "B3",
    "B4",
    "B5",
    "C1",
    "C2",
    "C3",
    "C4",
    "C5",
    "D1",
    "D2",
    "D3",
    "D4",
    "D5",
    "D7",
    "E1",
    "E2",
    "E3",
    "E4",
    "F1",
    "F2",
    "F3",
    "F4",
}


def _build_lpa_fact_tool_schema() -> dict:
    """Build the JSON Schema for the LPA fact-labeling tool."""
    return {
        "type": "object",
        "properties": {
            "fund_name": {"type": "string", "description": "基金名称"},
            "fund_type": {"type": "string", "description": "基金类型"},
            "domicile": {"type": "string", "description": "注册地"},
            "gp_name": {"type": "string", "description": "普通合伙人名称"},
            "manager_name": {"type": "string", "description": "管理人名称"},
            "gp_is_manager": {"type": "boolean", "description": "GP是否同时担任管理人"},
            "committed_capital": {"type": "string", "description": "认缴出资总额"},
            "management_fee_rate": {"type": "number", "description": "管理费率（小数）"},
            "management_fee_basis": {"type": "string", "description": "管理费计算基数类型"},
            "hurdle_rate": {"type": "number", "description": "优先回报率（小数）"},
            "gp_carry": {"type": "number", "description": "GP业绩报酬比例（小数）"},
            "investment_period_years": {"type": "integer", "description": "投资期（年）"},
            "exit_period_years": {"type": "integer", "description": "退出期（年）"},
            "extension_period_years": {"type": "integer", "description": "延长期（年）"},
            "lpac_approval_threshold": {"type": "number", "description": "LPAC审批门槛比例"},
            "lp_min_commitment": {"type": "string", "description": "LP最低出资额"},
            "gp_removal_for_cause": {"type": "string", "description": "GP有因除名条款"},
            "gp_removal_nofault_threshold": {
                "type": "number",
                "description": "GP无过错除名投票比例",
            },
            "key_persons": {
                "type": "array",
                "items": {"type": "string"},
                "description": "关键人士列表",
            },
            "dispute_resolution": {"type": "string", "description": "争议解决机构"},
        },
        "required": [],
    }


# Document type configurations
DOCUMENT_TYPE_CONFIGS: dict[str, dict] = {
    "lpa": {
        "name": "有限合伙协议 (LPA)",
        "report_title": "AI LPA 合同审查报告",
        "chapter_keywords": _LPA_CHAPTER_KEYWORDS,
        "entity_patterns": _LPA_ENTITY_PATTERNS,
        "fact_tool_schema": _build_lpa_fact_tool_schema(),
        "risk_rules": LPA_RULES,
        "rule_keyword_map": _LPA_RULE_KEYWORD_MAP,
        "simple_rule_ids": _LPA_SIMPLE_RULE_IDS,
        "complex_rule_ids": _LPA_COMPLEX_RULE_IDS,
        "prompt_templates": {
            "chapter_split": str(PROMPTS_DIR / "chapter_split.md"),
            "fact_labeling": str(PROMPTS_DIR / "fact_labeling.md"),
            "simple_review": str(PROMPTS_DIR / "simple_review.md"),
            "complex_review": str(PROMPTS_DIR / "complex_review.md"),
            "cross_check": str(PROMPTS_DIR / "cross_check.md"),
        },
    },
    "contract": {
        "name": "通用合同",
        "report_title": "AI 合同审查报告",
        "chapter_keywords": [
            "定义",
            "definitions",
            "interpretation",
            "释义",
            "标的",
            "subject matter",
            "scope",
            "价款",
            "价格",
            "price",
            "payment",
            "费用",
            "履行",
            "performance",
            "交付",
            "delivery",
            "违约",
            "default",
            "breach",
            "责任",
            "保密",
            "confidential",
            "保密条款",
            "知识产权",
            "intellectual property",
            "不可抗力",
            "force majeure",
            "争议解决",
            "dispute resolution",
            "仲裁",
            "诉讼",
            "合同终止",
            "termination",
            "解除",
            "转让",
            "assignment",
            "变更",
            "amendment",
            "通知",
            "notice",
            "适用法律",
            "governing law",
            "其他",
            "miscellaneous",
            "一般条款",
            "签署",
            "signature",
            "execution",
        ],
        "entity_patterns": [
            r"(?:甲方|乙方|丙方|买方|卖方|委托方|受托方|发包方|承包方|出租方|承租方)[：:\s]*([^\n,，。；;]+?(?:公司|企业|集团|Co\.|Ltd\.|LLP|Inc\.|Corp\.))",
        ],
        "fact_tool_schema": {
            "type": "object",
            "properties": {
                "party_a": {"type": "string", "description": "甲方名称"},
                "party_b": {"type": "string", "description": "乙方名称"},
                "contract_subject": {"type": "string", "description": "合同标的"},
                "contract_value": {"type": "string", "description": "合同金额"},
                "payment_terms": {"type": "string", "description": "付款条件"},
                "contract_term": {"type": "string", "description": "合同期限"},
                "delivery_date": {"type": "string", "description": "交付日期"},
                "governing_law": {"type": "string", "description": "适用法律"},
                "dispute_resolution": {"type": "string", "description": "争议解决方式"},
                "confidentiality": {"type": "boolean", "description": "是否包含保密条款"},
                "termination_conditions": {"type": "string", "description": "终止条件"},
            },
            "required": [],
        },
        "risk_rules": CONTRACT_RULES,
        "rule_keyword_map": {
            "A1": ["主体", "parties", "甲方", "乙方"],
            "A2": ["标的", "subject matter", "scope", "范围"],
            "A3": ["期限", "term", "续期", "renewal"],
            "A4": ["金额", "价格", "price", "payment", "付款"],
            "B1": ["违约", "default", "breach", "责任"],
            "B2": ["保密", "confidential", "保密条款"],
            "B3": ["知识产权", "intellectual property"],
            "B4": ["不可抗力", "force majeure"],
            "B5": ["竞业", "non-compete", "竞业限制"],
            "C1": ["争议", "dispute", "仲裁", "诉讼"],
            "C2": ["终止", "termination", "解除"],
            "C3": ["转让", "assignment", "分包"],
        },
        "simple_rule_ids": {"A5", "C4", "C5"},
        "complex_rule_ids": {
            "A1",
            "A2",
            "A3",
            "A4",
            "B1",
            "B2",
            "B3",
            "B4",
            "B5",
            "C1",
            "C2",
            "C3",
        },
        "prompt_templates": {
            "chapter_split": str(PROMPTS_DIR / "chapter_split.md"),
            "fact_labeling": str(PROMPTS_DIR / "fact_labeling.md"),
            "simple_review": str(PROMPTS_DIR / "simple_review.md"),
            "complex_review": str(PROMPTS_DIR / "complex_review.md"),
            "cross_check": str(PROMPTS_DIR / "cross_check.md"),
        },
    },
    "nda": {
        "name": "保密协议 (NDA)",
        "report_title": "AI NDA 合同审查报告",
        "chapter_keywords": [
            "定义",
            "definitions",
            "保密信息",
            "confidential information",
            "保密义务",
            "confidentiality obligation",
            "使用限制",
            "use restriction",
            "purpose",
            "期限",
            "term",
            "duration",
            "有效期",
            "返还",
            "return",
            "销毁",
            "destruction",
            "违约",
            "breach",
            "default",
            "责任",
            "救济",
            "remedy",
            "禁令",
            "injunction",
            "争议解决",
            "dispute resolution",
            "仲裁",
            "诉讼",
            "适用法律",
            "governing law",
            "转让",
            "assignment",
            "通知",
            "notice",
            "其他",
            "miscellaneous",
            "签署",
            "signature",
            "execution",
        ],
        "entity_patterns": [
            r"(?:甲方|乙方|丙方|披露方|接收方|Disclosing Party|Receiving Party)[：:\s]*([^\n,，。；;]+?(?:公司|企业|集团|Co\.|Ltd\.|LLP|Inc\.|Corp\.))",
        ],
        "fact_tool_schema": {
            "type": "object",
            "properties": {
                "disclosing_party": {"type": "string", "description": "披露方名称"},
                "receiving_party": {"type": "string", "description": "接收方名称"},
                "confidential_info_scope": {"type": "string", "description": "保密信息范围"},
                "confidentiality_period": {"type": "string", "description": "保密期限"},
                "purpose": {"type": "string", "description": "使用目的"},
                "governing_law": {"type": "string", "description": "适用法律"},
                "dispute_resolution": {"type": "string", "description": "争议解决方式"},
                "non_compete_included": {"type": "boolean", "description": "是否包含竞业限制条款"},
                "non_solicit_included": {"type": "boolean", "description": "是否包含非招揽条款"},
                "remedy_provisions": {"type": "string", "description": "救济措施"},
            },
            "required": [],
        },
        "risk_rules": NDA_RULES,
        "rule_keyword_map": {
            "A1": ["保密信息", "confidential information", "定义"],
            "A2": ["保密义务", "confidentiality obligation", "义务范围"],
            "A3": ["期限", "term", "duration", "保密期限"],
            "A4": ["关联方", "affiliate", "子公司"],
            "B1": ["使用限制", "use restriction", "目的", "purpose"],
            "B2": ["披露", "disclosure", "第三方"],
            "B3": ["返还", "return", "销毁", "destruction"],
            "B4": ["知识产权", "intellectual property"],
            "B5": ["竞业", "non-compete", "非招揽", "non-solicit"],
            "C1": ["违约", "breach", "救济", "remedy"],
            "C2": ["争议", "dispute", "仲裁", "诉讼"],
        },
        "simple_rule_ids": {"A4", "C3"},
        "complex_rule_ids": {"A1", "A2", "A3", "B1", "B2", "B3", "B4", "B5", "C1", "C2"},
        "prompt_templates": {
            "chapter_split": str(PROMPTS_DIR / "chapter_split.md"),
            "fact_labeling": str(PROMPTS_DIR / "fact_labeling.md"),
            "simple_review": str(PROMPTS_DIR / "simple_review.md"),
            "complex_review": str(PROMPTS_DIR / "complex_review.md"),
            "cross_check": str(PROMPTS_DIR / "cross_check.md"),
        },
    },
    "employment": {
        "name": "劳动合同",
        "report_title": "AI 劳动合同审查报告",
        "chapter_keywords": [
            "合同期限",
            "劳动期限",
            "contract term",
            "试用期",
            "probation",
            "工作内容",
            "工作岗位",
            "job description",
            "职责",
            "工作地点",
            "work location",
            "劳动报酬",
            "工资",
            "薪酬",
            "salary",
            "compensation",
            "工作时间",
            "工时",
            "working hours",
            "加班",
            "社会保险",
            "五险一金",
            "福利",
            "保密",
            "confidential",
            "竞业限制",
            "non-compete",
            "培训",
            "服务期",
            "training",
            "知识产权",
            "intellectual property",
            "合同解除",
            "termination",
            "解除",
            "争议",
            "dispute",
            "仲裁",
            "其他",
            "miscellaneous",
            "签署",
            "signature",
        ],
        "entity_patterns": [
            r"(?:用人单位|甲方|乙方|雇主|Employee|Employer)[：:\s]*([^\n,，。；;]+?(?:公司|企业|集团|个人|Co\.|Ltd\.|LLP|Inc\.|Corp\.))",
        ],
        "fact_tool_schema": {
            "type": "object",
            "properties": {
                "employer_name": {"type": "string", "description": "用人单位名称"},
                "employee_name": {"type": "string", "description": "员工姓名"},
                "position": {"type": "string", "description": "工作岗位"},
                "contract_type": {
                    "type": "string",
                    "description": "合同类型（固定期限/无固定期限）",
                },
                "contract_term": {"type": "string", "description": "合同期限"},
                "probation_period": {"type": "string", "description": "试用期"},
                "salary": {"type": "string", "description": "工资标准"},
                "work_location": {"type": "string", "description": "工作地点"},
                "working_hours": {"type": "string", "description": "工时制度"},
                "non_compete_included": {"type": "boolean", "description": "是否包含竞业限制"},
                "non_compete_compensation": {"type": "string", "description": "竞业限制补偿金"},
                "social_insurance": {"type": "boolean", "description": "是否约定缴纳社保"},
            },
            "required": [],
        },
        "risk_rules": EMPLOYMENT_RULES,
        "rule_keyword_map": {
            "A1": ["合同期限", "contract term", "试用期", "probation"],
            "A2": ["工作内容", "job description", "工作岗位", "工作地点"],
            "A3": ["工资", "salary", "劳动报酬", "薪酬"],
            "A4": ["工作时间", "working hours", "加班", "工时"],
            "A5": ["社保", "social insurance", "五险一金", "福利"],
            "B1": ["竞业限制", "non-compete", "竞业"],
            "B2": ["保密", "confidential", "保密条款"],
            "B3": ["培训", "training", "服务期"],
            "B4": ["知识产权", "intellectual property"],
            "C1": ["解除", "termination", "终止"],
            "C2": ["争议", "dispute", "仲裁"],
            "C3": ["违约", "breach", "违约金"],
        },
        "simple_rule_ids": {"A5", "B5", "C3"},
        "complex_rule_ids": {"A1", "A2", "A3", "A4", "B1", "B2", "B3", "B4", "C1", "C2"},
        "prompt_templates": {
            "chapter_split": str(PROMPTS_DIR / "chapter_split.md"),
            "fact_labeling": str(PROMPTS_DIR / "fact_labeling.md"),
            "simple_review": str(PROMPTS_DIR / "simple_review.md"),
            "complex_review": str(PROMPTS_DIR / "complex_review.md"),
            "cross_check": str(PROMPTS_DIR / "cross_check.md"),
        },
    },
    "lease": {
        "name": "租赁合同",
        "report_title": "AI 租赁合同审查报告",
        "chapter_keywords": [
            "定义",
            "definitions",
            "租赁物",
            "premises",
            "租赁标的",
            "租金",
            "rent",
            "lease payment",
            "租赁期限",
            "lease term",
            "term",
            "维修",
            "maintenance",
            "repair",
            "转租",
            "sublease",
            "subletting",
            "装修",
            "renovation",
            "improvement",
            "违约",
            "default",
            "breach",
            "合同终止",
            "termination",
            "解除",
            "争议解决",
            "dispute resolution",
            "其他",
            "miscellaneous",
            "签署",
            "signature",
        ],
        "entity_patterns": [
            r"(?:出租方|承租方|甲方|乙方|房东|租户|Landlord|Tenant)[：:\s]*([^\n,，。；;]+?(?:公司|企业|集团|个人|Co\.|Ltd\.|LLP|Inc\.|Corp\.))",
        ],
        "fact_tool_schema": {
            "type": "object",
            "properties": {
                "landlord_name": {"type": "string", "description": "出租方名称"},
                "tenant_name": {"type": "string", "description": "承租方名称"},
                "premises_address": {"type": "string", "description": "租赁物地址"},
                "premises_area": {"type": "string", "description": "租赁面积"},
                "lease_purpose": {"type": "string", "description": "租赁用途"},
                "lease_term": {"type": "string", "description": "租赁期限"},
                "rent_amount": {"type": "string", "description": "租金金额"},
                "payment_cycle": {"type": "string", "description": "支付周期"},
                "deposit_amount": {"type": "string", "description": "押金金额"},
                "renewal_terms": {"type": "string", "description": "续租条件"},
            },
            "required": [],
        },
        "risk_rules": LEASE_RULES,
        "rule_keyword_map": {
            "A1": ["租赁物", "premises", "地址", "面积"],
            "A2": ["期限", "term", "租期", "续租"],
            "A3": ["租金", "rent", "付款", "押金"],
            "A4": ["主体", "parties", "出租方", "承租方"],
            "B1": ["维修", "maintenance", "保养"],
            "B2": ["转租", "sublease", "分租"],
            "B3": ["装修", "renovation", "改造"],
            "B4": ["违约", "default", "breach"],
            "C1": ["登记", "备案", "registration"],
            "C2": ["终止", "termination", "交接"],
            "C3": ["争议", "dispute", "仲裁"],
        },
        "simple_rule_ids": {"C1", "C3"},
        "complex_rule_ids": {"A1", "A2", "A3", "A4", "B1", "B2", "B3", "B4", "C2"},
        "prompt_templates": {
            "chapter_split": str(PROMPTS_DIR / "chapter_split.md"),
            "fact_labeling": str(PROMPTS_DIR / "fact_labeling.md"),
            "simple_review": str(PROMPTS_DIR / "simple_review.md"),
            "complex_review": str(PROMPTS_DIR / "complex_review.md"),
            "cross_check": str(PROMPTS_DIR / "cross_check.md"),
        },
    },
    "loan": {
        "name": "借款合同",
        "report_title": "AI 借款合同审查报告",
        "chapter_keywords": [
            "定义",
            "definitions",
            "借款",
            "loan",
            "借款金额",
            "loan amount",
            "principal",
            "利率",
            "interest rate",
            "利息",
            "借款期限",
            "loan term",
            "maturity",
            "还款",
            "repayment",
            "偿还",
            "担保",
            "guarantee",
            "security",
            "抵押",
            "质押",
            "违约",
            "default",
            "逾期",
            "合同终止",
            "termination",
            "争议解决",
            "dispute resolution",
            "其他",
            "miscellaneous",
            "签署",
            "signature",
        ],
        "entity_patterns": [
            r"(?:出借人|借款人|甲方|乙方|贷款人|Lender|Borrower)[：:\s]*([^\n,，。；;]+?(?:公司|企业|集团|银行|个人|Co\.|Ltd\.|LLP|Inc\.|Corp\.))",
        ],
        "fact_tool_schema": {
            "type": "object",
            "properties": {
                "lender_name": {"type": "string", "description": "出借人名称"},
                "borrower_name": {"type": "string", "description": "借款人名称"},
                "loan_amount": {"type": "string", "description": "借款金额"},
                "interest_rate": {"type": "string", "description": "利率"},
                "loan_term": {"type": "string", "description": "借款期限"},
                "repayment_method": {"type": "string", "description": "还款方式"},
                "guarantee_type": {"type": "string", "description": "担保方式"},
                "loan_purpose": {"type": "string", "description": "借款用途"},
                "penalty_rate": {"type": "string", "description": "罚息利率"},
            },
            "required": [],
        },
        "risk_rules": LOAN_RULES,
        "rule_keyword_map": {
            "A1": ["主体", "parties", "出借人", "借款人"],
            "A2": ["金额", "amount", "借款金额"],
            "A3": ["期限", "term", "借款期限"],
            "A4": ["利率", "interest", "利息"],
            "B1": ["担保", "guarantee", "抵押", "质押"],
            "B2": ["还款", "repayment", "偿还"],
            "B3": ["违约", "default", "罚息"],
            "B4": ["用途", "purpose", "借款用途"],
            "C1": ["生效", "effectiveness", "交付"],
            "C2": ["争议", "dispute", "仲裁"],
            "C3": ["税费", "tax", "印花税"],
        },
        "simple_rule_ids": {"A1", "C2", "C3"},
        "complex_rule_ids": {"A2", "A3", "A4", "B1", "B2", "B3", "B4", "C1"},
        "prompt_templates": {
            "chapter_split": str(PROMPTS_DIR / "chapter_split.md"),
            "fact_labeling": str(PROMPTS_DIR / "fact_labeling.md"),
            "simple_review": str(PROMPTS_DIR / "simple_review.md"),
            "complex_review": str(PROMPTS_DIR / "complex_review.md"),
            "cross_check": str(PROMPTS_DIR / "cross_check.md"),
        },
    },
    "sales": {
        "name": "买卖合同",
        "report_title": "AI 买卖合同审查报告",
        "chapter_keywords": [
            "定义",
            "definitions",
            "标的物",
            "subject matter",
            "价款",
            "价格",
            "price",
            "payment",
            "交付",
            "delivery",
            "交货",
            "验收",
            "acceptance",
            "inspection",
            "质量",
            "quality",
            "warranty",
            "违约",
            "default",
            "breach",
            "包装",
            "packaging",
            "运输",
            "合同终止",
            "termination",
            "争议解决",
            "dispute resolution",
            "其他",
            "miscellaneous",
            "签署",
            "signature",
        ],
        "entity_patterns": [
            r"(?:买方|卖方|甲方|乙方|采购方|供应方|Buyer|Seller)[：:\s]*([^\n,，。；;]+?(?:公司|企业|集团|Co\.|Ltd\.|LLP|Inc\.|Corp\.))",
        ],
        "fact_tool_schema": {
            "type": "object",
            "properties": {
                "buyer_name": {"type": "string", "description": "买方名称"},
                "seller_name": {"type": "string", "description": "卖方名称"},
                "product_name": {"type": "string", "description": "标的物名称"},
                "product_spec": {"type": "string", "description": "标的物规格"},
                "quantity": {"type": "string", "description": "数量"},
                "unit_price": {"type": "string", "description": "单价"},
                "total_price": {"type": "string", "description": "总价"},
                "delivery_date": {"type": "string", "description": "交付日期"},
                "delivery_location": {"type": "string", "description": "交付地点"},
                "payment_terms": {"type": "string", "description": "付款条件"},
            },
            "required": [],
        },
        "risk_rules": SALES_RULES,
        "rule_keyword_map": {
            "A1": ["主体", "parties", "买方", "卖方"],
            "A2": ["标的物", "subject matter", "规格", "数量"],
            "A3": ["价格", "price", "付款", "金额"],
            "A4": ["交付", "delivery", "验收", "运输"],
            "B1": ["质量", "quality", "售后", "保修"],
            "B2": ["违约", "default", "breach"],
            "B3": ["知识产权", "IP"],
            "B4": ["保密", "confidential"],
            "C1": ["不可抗力", "force majeure"],
            "C2": ["终止", "termination", "解除"],
            "C3": ["争议", "dispute", "仲裁"],
        },
        "simple_rule_ids": {"A1", "B4", "C3"},
        "complex_rule_ids": {"A2", "A3", "A4", "B1", "B2", "B3", "C1", "C2"},
        "prompt_templates": {
            "chapter_split": str(PROMPTS_DIR / "chapter_split.md"),
            "fact_labeling": str(PROMPTS_DIR / "fact_labeling.md"),
            "simple_review": str(PROMPTS_DIR / "simple_review.md"),
            "complex_review": str(PROMPTS_DIR / "complex_review.md"),
            "cross_check": str(PROMPTS_DIR / "cross_check.md"),
        },
    },
    "service": {
        "name": "服务合同",
        "report_title": "AI 服务合同审查报告",
        "chapter_keywords": [
            "定义",
            "definitions",
            "服务内容",
            "scope of services",
            "服务期限",
            "service term",
            "服务费用",
            "service fee",
            "报酬",
            "服务质量",
            "service quality",
            "KPI",
            "SLA",
            "人员",
            "personnel",
            "团队",
            "保密",
            "confidential",
            "知识产权",
            "intellectual property",
            "违约",
            "default",
            "breach",
            "合同终止",
            "termination",
            "争议解决",
            "dispute resolution",
            "其他",
            "miscellaneous",
            "签署",
            "signature",
        ],
        "entity_patterns": [
            r"(?:委托方|受托方|甲方|乙方|服务方|Client|Service Provider)[：:\s]*([^\n,，。；;]+?(?:公司|企业|集团|Co\.|Ltd\.|LLP|Inc\.|Corp\.))",
        ],
        "fact_tool_schema": {
            "type": "object",
            "properties": {
                "client_name": {"type": "string", "description": "委托方名称"},
                "provider_name": {"type": "string", "description": "受托方名称"},
                "service_scope": {"type": "string", "description": "服务内容"},
                "service_term": {"type": "string", "description": "服务期限"},
                "service_fee": {"type": "string", "description": "服务费用"},
                "payment_method": {"type": "string", "description": "付款方式"},
                "kpi_sla": {"type": "string", "description": "服务质量标准"},
                "key_personnel": {"type": "string", "description": "核心人员"},
            },
            "required": [],
        },
        "risk_rules": SERVICE_RULES,
        "rule_keyword_map": {
            "A1": ["主体", "parties", "委托方", "受托方"],
            "A2": ["服务内容", "scope", "范围"],
            "A3": ["期限", "term", "服务期限"],
            "A4": ["费用", "fee", "报酬", "付款"],
            "B1": ["质量", "quality", "KPI", "SLA"],
            "B2": ["人员", "personnel", "团队"],
            "B3": ["保密", "confidential", "数据"],
            "B4": ["知识产权", "IP"],
            "C1": ["违约", "default", "breach"],
            "C2": ["终止", "termination", "交接"],
            "C3": ["争议", "dispute", "仲裁"],
        },
        "simple_rule_ids": {"A1", "C3"},
        "complex_rule_ids": {"A2", "A3", "A4", "B1", "B2", "B3", "B4", "C1", "C2"},
        "prompt_templates": {
            "chapter_split": str(PROMPTS_DIR / "chapter_split.md"),
            "fact_labeling": str(PROMPTS_DIR / "fact_labeling.md"),
            "simple_review": str(PROMPTS_DIR / "simple_review.md"),
            "complex_review": str(PROMPTS_DIR / "complex_review.md"),
            "cross_check": str(PROMPTS_DIR / "cross_check.md"),
        },
    },
    "ip_license": {
        "name": "知识产权许可",
        "report_title": "AI 知识产权许可协议审查报告",
        "chapter_keywords": [
            "定义",
            "definitions",
            "许可",
            "license",
            "许可范围",
            "scope of license",
            "许可方式",
            "许可费",
            "royalty",
            "许可使用费",
            "许可期限",
            "license term",
            "知识产权",
            "intellectual property",
            "专利",
            "商标",
            "著作权",
            "保密",
            "confidential",
            "改进",
            "improvement",
            "违约",
            "default",
            "breach",
            "终止",
            "termination",
            "争议解决",
            "dispute resolution",
            "其他",
            "miscellaneous",
            "签署",
            "signature",
        ],
        "entity_patterns": [
            r"(?:许可方|被许可方|甲方|乙方|Licensor|Licensee)[：:\s]*([^\n,，。；;]+?(?:公司|企业|集团|个人|Co\.|Ltd\.|LLP|Inc\.|Corp\.))",
        ],
        "fact_tool_schema": {
            "type": "object",
            "properties": {
                "licensor_name": {"type": "string", "description": "许可方名称"},
                "licensee_name": {"type": "string", "description": "被许可方名称"},
                "ip_type": {"type": "string", "description": "知识产权类型"},
                "ip_number": {"type": "string", "description": "权利证书编号"},
                "license_type": {"type": "string", "description": "许可方式（独占/排他/普通）"},
                "license_scope": {"type": "string", "description": "许可范围"},
                "license_term": {"type": "string", "description": "许可期限"},
                "royalty_amount": {"type": "string", "description": "许可费"},
            },
            "required": [],
        },
        "risk_rules": IP_LICENSE_RULES,
        "rule_keyword_map": {
            "A1": ["许可方", "被许可方", "主体"],
            "A2": ["知识产权", "IP", "专利", "商标", "著作权"],
            "A3": ["许可范围", "scope", "许可方式", "独占", "排他"],
            "A4": ["期限", "term", "许可期限"],
            "B1": ["许可费", "royalty", "费用"],
            "B2": ["保护", "protection", "侵权"],
            "B3": ["改进", "improvement", "回授"],
            "B4": ["保密", "confidential"],
            "C1": ["违约", "default", "终止"],
            "C2": ["侵权", "infringement", "担保"],
            "C3": ["争议", "dispute", "仲裁"],
        },
        "simple_rule_ids": {"A1", "C3"},
        "complex_rule_ids": {"A2", "A3", "A4", "B1", "B2", "B3", "B4", "C1", "C2"},
        "prompt_templates": {
            "chapter_split": str(PROMPTS_DIR / "chapter_split.md"),
            "fact_labeling": str(PROMPTS_DIR / "fact_labeling.md"),
            "simple_review": str(PROMPTS_DIR / "simple_review.md"),
            "complex_review": str(PROMPTS_DIR / "complex_review.md"),
            "cross_check": str(PROMPTS_DIR / "cross_check.md"),
        },
    },
    "equity_investment": {
        "name": "股权投资协议",
        "report_title": "AI 股权投资协议审查报告",
        "chapter_keywords": [
            "定义",
            "definitions",
            "投资",
            "investment",
            "估值",
            "valuation",
            "投资金额",
            "交割",
            "closing",
            "先决条件",
            "反稀释",
            "anti-dilution",
            "优先权",
            "priority",
            "优先认购",
            "优先购买",
            "共同出售",
            "回购",
            "redemption",
            "buyback",
            "陈述与保证",
            "representations",
            "warranties",
            "竞业",
            "non-compete",
            "违约",
            "default",
            "终止",
            "termination",
            "争议解决",
            "dispute resolution",
            "其他",
            "miscellaneous",
            "签署",
            "signature",
        ],
        "entity_patterns": [
            r"(?:投资方|目标公司|创始人|甲方|乙方|Investor|Target Company)[：:\s]*([^\n,，。；;]+?(?:公司|企业|集团|基金|合伙|Co\.|Ltd\.|LLP|Inc\.|Corp\.))",
        ],
        "fact_tool_schema": {
            "type": "object",
            "properties": {
                "investor_name": {"type": "string", "description": "投资方名称"},
                "target_company": {"type": "string", "description": "目标公司名称"},
                "investment_amount": {"type": "string", "description": "投资金额"},
                "pre_money_valuation": {"type": "string", "description": "投前估值"},
                "post_money_valuation": {"type": "string", "description": "投后估值"},
                "equity_percentage": {"type": "string", "description": "股权比例"},
                "closing_conditions": {"type": "string", "description": "交割条件"},
                "anti_dilution": {"type": "string", "description": "反稀释条款"},
                "board_seats": {"type": "string", "description": "董事会席位"},
            },
            "required": [],
        },
        "risk_rules": EQUITY_INVESTMENT_RULES,
        "rule_keyword_map": {
            "A1": ["投资方", "目标公司", "主体"],
            "A2": ["估值", "valuation", "投资金额"],
            "A3": ["交割", "closing", "先决条件"],
            "A4": ["资金用途", "use of proceeds"],
            "B1": ["反稀释", "anti-dilution"],
            "B2": ["优先权", "priority", "优先认购", "优先购买"],
            "B3": ["回购", "redemption", "buyback"],
            "B4": ["信息权", "information right", "检查权"],
            "C1": ["竞业", "non-compete", "创始人"],
            "C2": ["陈述", "representations", "保证"],
            "C3": ["争议", "dispute", "仲裁"],
        },
        "simple_rule_ids": {"A1", "C3"},
        "complex_rule_ids": {"A2", "A3", "A4", "B1", "B2", "B3", "B4", "C1", "C2"},
        "prompt_templates": {
            "chapter_split": str(PROMPTS_DIR / "chapter_split.md"),
            "fact_labeling": str(PROMPTS_DIR / "fact_labeling.md"),
            "simple_review": str(PROMPTS_DIR / "simple_review.md"),
            "complex_review": str(PROMPTS_DIR / "complex_review.md"),
            "cross_check": str(PROMPTS_DIR / "cross_check.md"),
        },
    },
    "construction": {
        "name": "建设工程合同",
        "report_title": "AI 建设工程合同审查报告",
        "chapter_keywords": [
            "定义",
            "definitions",
            "工程",
            "construction",
            "project",
            "工程范围",
            "scope of work",
            "工期",
            "construction period",
            "进度",
            "工程价款",
            "contract price",
            "造价",
            "质量",
            "quality",
            "验收",
            "安全",
            "safety",
            "文明施工",
            "变更",
            "change order",
            "签证",
            "分包",
            "subcontracting",
            "违约",
            "default",
            "竣工验收",
            "completion",
            "acceptance",
            "保修",
            "warranty",
            "defects",
            "争议解决",
            "dispute resolution",
            "其他",
            "miscellaneous",
            "签署",
            "signature",
        ],
        "entity_patterns": [
            r"(?:发包方|承包方|甲方|乙方|业主|Owner|Contractor)[：:\s]*([^\n,，。；;]+?(?:公司|企业|集团|Co\.|Ltd\.|LLP|Inc\.|Corp\.))",
        ],
        "fact_tool_schema": {
            "type": "object",
            "properties": {
                "owner_name": {"type": "string", "description": "发包方名称"},
                "contractor_name": {"type": "string", "description": "承包方名称"},
                "project_name": {"type": "string", "description": "工程名称"},
                "project_location": {"type": "string", "description": "工程地点"},
                "contract_price": {"type": "string", "description": "合同价款"},
                "pricing_method": {"type": "string", "description": "计价方式"},
                "construction_period": {"type": "string", "description": "工期"},
                "quality_standard": {"type": "string", "description": "质量标准"},
                "warranty_period": {"type": "string", "description": "保修期"},
            },
            "required": [],
        },
        "risk_rules": CONSTRUCTION_RULES,
        "rule_keyword_map": {
            "A1": ["发包方", "承包方", "主体", "资质"],
            "A2": ["工程范围", "scope", "工程内容"],
            "A3": ["工期", "period", "进度", "竣工"],
            "A4": ["价款", "price", "付款", "结算"],
            "B1": ["质量", "quality", "验收"],
            "B2": ["安全", "safety", "文明施工"],
            "B3": ["变更", "change", "签证"],
            "B4": ["分包", "subcontracting"],
            "C1": ["违约", "default"],
            "C2": ["竣工验收", "completion", "结算"],
            "C3": ["争议", "dispute", "仲裁"],
        },
        "simple_rule_ids": {"C3"},
        "complex_rule_ids": {"A1", "A2", "A3", "A4", "B1", "B2", "B3", "B4", "C1", "C2"},
        "prompt_templates": {
            "chapter_split": str(PROMPTS_DIR / "chapter_split.md"),
            "fact_labeling": str(PROMPTS_DIR / "fact_labeling.md"),
            "simple_review": str(PROMPTS_DIR / "simple_review.md"),
            "complex_review": str(PROMPTS_DIR / "complex_review.md"),
            "cross_check": str(PROMPTS_DIR / "cross_check.md"),
        },
    },
    "articles_of_association": {
        "name": "公司章程",
        "report_title": "AI 公司章程审查报告",
        "chapter_keywords": [
            "公司名称",
            "公司住所",
            "经营范围",
            "注册资本",
            "股东",
            "出资",
            "股东会",
            "股东大会",
            "董事会",
            "执行董事",
            "监事会",
            "监事",
            "法定代表人",
            "利润分配",
            "分红",
            "股权转让",
            "转让",
            "章程修改",
            "修改",
            "解散",
            "清算",
            "争议解决",
            "其他",
            "附则",
        ],
        "entity_patterns": [
            r"(?:公司|股东|发起人|董事|监事|Company|Shareholder)[：:\s]*([^\n,，。；;]+?(?:公司|企业|集团|个人|Co\.|Ltd\.|LLP|Inc\.|Corp\.))",
        ],
        "fact_tool_schema": {
            "type": "object",
            "properties": {
                "company_name": {"type": "string", "description": "公司名称"},
                "company_type": {"type": "string", "description": "公司类型"},
                "registered_capital": {"type": "string", "description": "注册资本"},
                "business_scope": {"type": "string", "description": "经营范围"},
                "shareholders": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "股东列表",
                },
                "legal_representative": {"type": "string", "description": "法定代表人"},
                "board_structure": {"type": "string", "description": "董事会结构"},
                "supervisor_structure": {"type": "string", "description": "监事会结构"},
            },
            "required": [],
        },
        "risk_rules": ARTICLES_OF_ASSOCIATION_RULES,
        "rule_keyword_map": {
            "A1": ["公司名称", "住所", "经营范围"],
            "A2": ["股东", "出资", "注册资本"],
            "A3": ["股东会", "董事会", "监事会"],
            "A4": ["利润", "分红", "分配"],
            "B1": ["股权转让", "转让", "优先购买"],
            "B2": ["退出", "回购", "减资"],
            "B3": ["知情权", "查阅", "监督"],
            "B4": ["竞业", "同业竞争"],
            "C1": ["僵局", "解散"],
            "C2": ["章程修改", "修改"],
            "C3": ["争议", "dispute"],
        },
        "simple_rule_ids": {"A1", "C2", "C3"},
        "complex_rule_ids": {"A2", "A3", "A4", "B1", "B2", "B3", "B4", "C1"},
        "prompt_templates": {
            "chapter_split": str(PROMPTS_DIR / "chapter_split.md"),
            "fact_labeling": str(PROMPTS_DIR / "fact_labeling.md"),
            "simple_review": str(PROMPTS_DIR / "simple_review.md"),
            "complex_review": str(PROMPTS_DIR / "complex_review.md"),
            "cross_check": str(PROMPTS_DIR / "cross_check.md"),
        },
    },
    "marital_property": {
        "name": "婚姻财产协议",
        "report_title": "AI 婚姻财产协议审查报告",
        "chapter_keywords": [
            "双方信息",
            "婚姻状况",
            "财产范围",
            "财产清单",
            "房产",
            "不动产",
            "存款",
            "投资",
            "股权",
            "车辆",
            "动产",
            "债务",
            "债权",
            "收入",
            "工资",
            "赠与",
            "继承",
            "补偿",
            "帮助",
            "变更",
            "撤销",
            "生效",
            "公证",
            "争议",
            "其他",
            "签署",
        ],
        "entity_patterns": [
            r"(?:男方|女方|丈夫|妻子|甲方|乙方|Husband|Wife)[：:\s]*([^\n,，。；;]+)",
        ],
        "fact_tool_schema": {
            "type": "object",
            "properties": {
                "husband_name": {"type": "string", "description": "男方姓名"},
                "wife_name": {"type": "string", "description": "女方姓名"},
                "marriage_date": {"type": "string", "description": "结婚日期"},
                "property_scope": {"type": "string", "description": "财产范围"},
                "real_estate": {"type": "string", "description": "房产信息"},
                "vehicles": {"type": "string", "description": "车辆信息"},
                "investments": {"type": "string", "description": "投资信息"},
                "debt_arrangement": {"type": "string", "description": "债务安排"},
                "notarized": {"type": "boolean", "description": "是否公证"},
            },
            "required": [],
        },
        "risk_rules": MARITAL_PROPERTY_RULES,
        "rule_keyword_map": {
            "A1": ["身份", "姓名", "婚姻"],
            "A2": ["财产范围", "财产清单", "房产", "存款"],
            "A3": ["归属", "各自所有", "共同所有"],
            "B1": ["债务", "共同债务", "连带"],
            "B2": ["收入", "工资", "开支"],
            "B3": ["赠与", "继承"],
            "B4": ["补偿", "帮助"],
            "C1": ["变更", "撤销"],
            "C2": ["生效", "公证"],
            "C3": ["争议"],
        },
        "simple_rule_ids": {"A1", "C3"},
        "complex_rule_ids": {"A2", "A3", "B1", "B2", "B3", "B4", "C1", "C2"},
        "prompt_templates": {
            "chapter_split": str(PROMPTS_DIR / "chapter_split.md"),
            "fact_labeling": str(PROMPTS_DIR / "fact_labeling.md"),
            "simple_review": str(PROMPTS_DIR / "simple_review.md"),
            "complex_review": str(PROMPTS_DIR / "complex_review.md"),
            "cross_check": str(PROMPTS_DIR / "cross_check.md"),
        },
    },
    "will_estate": {
        "name": "遗嘱/继承",
        "report_title": "AI 遗嘱/继承文件审查报告",
        "chapter_keywords": [
            "立遗嘱人",
            "遗嘱人",
            "遗产",
            "财产",
            "继承人",
            "受遗赠人",
            "房产",
            "不动产",
            "存款",
            "投资",
            "遗嘱形式",
            "自书遗嘱",
            "代书遗嘱",
            "公证遗嘱",
            "见证人",
            "遗嘱执行",
            "执行人",
            "债务",
            "清偿",
            "变更",
            "撤销",
            "争议",
            "其他",
            "签署",
        ],
        "entity_patterns": [
            r"(?:立遗嘱人|遗嘱人|继承人|受遗赠人|见证人|Testator|Beneficiary)[：:\s]*([^\n,，。；;]+)",
        ],
        "fact_tool_schema": {
            "type": "object",
            "properties": {
                "testator_name": {"type": "string", "description": "立遗嘱人姓名"},
                "testator_id": {"type": "string", "description": "立遗嘱人身份证号"},
                "will_type": {"type": "string", "description": "遗嘱形式"},
                "estate_scope": {"type": "string", "description": "遗产范围"},
                "beneficiaries": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "继承人/受遗赠人列表",
                },
                "witnesses": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "见证人列表",
                },
                "executor": {"type": "string", "description": "遗嘱执行人"},
                "special_conditions": {"type": "string", "description": "特殊条件或负担"},
            },
            "required": [],
        },
        "risk_rules": WILL_ESTATE_RULES,
        "rule_keyword_map": {
            "A1": ["立遗嘱人", "身份", "行为能力"],
            "A2": ["遗产", "财产范围", "财产清单"],
            "A3": ["继承人", "受遗赠人", "必留份"],
            "B1": ["遗嘱形式", "自书", "代书", "打印", "公证"],
            "B2": ["见证人", "资格"],
            "B3": ["合法性", "公序良俗"],
            "C1": ["变更", "撤销", "多份遗嘱"],
            "C2": ["遗嘱执行", "执行人"],
            "C3": ["债务", "清偿"],
        },
        "simple_rule_ids": {"A1", "C2", "C3"},
        "complex_rule_ids": {"A2", "A3", "B1", "B2", "B3", "C1"},
        "prompt_templates": {
            "chapter_split": str(PROMPTS_DIR / "chapter_split.md"),
            "fact_labeling": str(PROMPTS_DIR / "fact_labeling.md"),
            "simple_review": str(PROMPTS_DIR / "simple_review.md"),
            "complex_review": str(PROMPTS_DIR / "complex_review.md"),
            "cross_check": str(PROMPTS_DIR / "cross_check.md"),
        },
    },
}


def get_document_type_config(document_type: str) -> dict:
    """Get configuration for a document type.

    Args:
        document_type: The document type key.

    Returns:
        Configuration dict for the given document type.

    Raises:
        KeyError: If the document type is not registered.
    """
    if document_type not in DOCUMENT_TYPE_CONFIGS:
        raise KeyError(
            f"Unknown document type: {document_type}. Available: {list(DOCUMENT_TYPE_CONFIGS.keys())}"
        )
    return DOCUMENT_TYPE_CONFIGS[document_type]
