
"""add user llm config fields

Revision ID: bc01a01ab35c
Revises: 
Create Date: 2026-05-04 20:03:27.826399

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bc01a01ab35c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('llm_provider', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('ai_model', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('openai_api_key', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('anthropic_api_key', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('llm_base_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'llm_base_url')
    op.drop_column('users', 'anthropic_api_key')
    op.drop_column('users', 'openai_api_key')
    op.drop_column('users', 'ai_model')
    op.drop_column('users', 'llm_provider')
    # ### end Alembic commands ###
