"""Configuration for construction document type."""

from app.agents.rules.construction_rules import CONSTRUCTION_RULES

CONFIG = {
        "name": "建设工程合同",
        "report_title": "AI 建设工程合同审查报告",
        "chapter_keywords": [
            "定义",
            "definitions",
            "工程",
            "construction",
            "project",
            "工程范围",
            "scope of work",
            "工期",
            "construction period",
            "进度",
            "工程价款",
            "contract price",
            "造价",
            "质量",
            "quality",
            "验收",
            "安全",
            "safety",
            "文明施工",
            "变更",
            "change order",
            "签证",
            "分包",
            "subcontracting",
            "违约",
            "default",
            "竣工验收",
            "completion",
            "acceptance",
            "保修",
            "warranty",
            "defects",
            "争议解决",
            "dispute resolution",
            "其他",
            "miscellaneous",
            "签署",
            "signature",
        ],
        "entity_patterns": [
            r"(?:发包方|承包方|甲方|乙方|业主|Owner|Contractor)[：:\s]*([^\n,，。；;]+?(?:公司|企业|集团|Co\.|Ltd\.|LLP|Inc\.|Corp\.))",
        ],
        "fact_tool_schema": {
            "type": "object",
            "properties": {
                "owner_name": {"type": "string", "description": "发包方名称"},
                "contractor_name": {"type": "string", "description": "承包方名称"},
                "project_name": {"type": "string", "description": "工程名称"},
                "project_location": {"type": "string", "description": "工程地点"},
                "contract_price": {"type": "string", "description": "合同价款"},
                "pricing_method": {"type": "string", "description": "计价方式"},
                "construction_period": {"type": "string", "description": "工期"},
                "quality_standard": {"type": "string", "description": "质量标准"},
                "warranty_period": {"type": "string", "description": "保修期"},
            },
            "required": [],
        },
        "risk_rules": CONSTRUCTION_RULES,
        "rule_keyword_map": {
            "A1": ["发包方", "承包方", "主体", "资质"],
            "A2": ["工程范围", "scope", "工程内容"],
            "A3": ["工期", "period", "进度", "竣工"],
            "A4": ["价款", "price", "付款", "结算"],
            "B1": ["质量", "quality", "验收"],
            "B2": ["安全", "safety", "文明施工"],
            "B3": ["变更", "change", "签证"],
            "B4": ["分包", "subcontracting"],
            "C1": ["违约", "default"],
            "C2": ["竣工验收", "completion", "结算"],
            "C3": ["争议", "dispute", "仲裁"],
        },
        "simple_rule_ids": {"C3"},
        "complex_rule_ids": {"A1", "A2", "A3", "A4", "B1", "B2", "B3", "B4", "C1", "C2"}
}
