"""Configuration for contract document type."""

from app.agents.rules.contract_rules import CONTRACT_RULES

CONFIG = {
        "name": "通用合同",
        "report_title": "AI 合同审查报告",
        "chapter_keywords": [
            "定义",
            "definitions",
            "interpretation",
            "释义",
            "标的",
            "subject matter",
            "scope",
            "价款",
            "价格",
            "price",
            "payment",
            "费用",
            "履行",
            "performance",
            "交付",
            "delivery",
            "违约",
            "default",
            "breach",
            "责任",
            "保密",
            "confidential",
            "保密条款",
            "知识产权",
            "intellectual property",
            "不可抗力",
            "force majeure",
            "争议解决",
            "dispute resolution",
            "仲裁",
            "诉讼",
            "合同终止",
            "termination",
            "解除",
            "转让",
            "assignment",
            "变更",
            "amendment",
            "通知",
            "notice",
            "适用法律",
            "governing law",
            "其他",
            "miscellaneous",
            "一般条款",
            "签署",
            "signature",
            "execution",
        ],
        "entity_patterns": [
            r"(?:甲方|乙方|丙方|买方|卖方|委托方|受托方|发包方|承包方|出租方|承租方)[：:\s]*([^\n,，。；;]+?(?:公司|企业|集团|Co\.|Ltd\.|LLP|Inc\.|Corp\.))",
        ],
        "fact_tool_schema": {
            "type": "object",
            "properties": {
                "party_a": {"type": "string", "description": "甲方名称"},
                "party_b": {"type": "string", "description": "乙方名称"},
                "contract_subject": {"type": "string", "description": "合同标的"},
                "contract_value": {"type": "string", "description": "合同金额"},
                "payment_terms": {"type": "string", "description": "付款条件"},
                "contract_term": {"type": "string", "description": "合同期限"},
                "delivery_date": {"type": "string", "description": "交付日期"},
                "governing_law": {"type": "string", "description": "适用法律"},
                "dispute_resolution": {"type": "string", "description": "争议解决方式"},
                "confidentiality": {"type": "boolean", "description": "是否包含保密条款"},
                "termination_conditions": {"type": "string", "description": "终止条件"},
            },
            "required": [],
        },
        "risk_rules": CONTRACT_RULES,
        "rule_keyword_map": {
            "A1": ["主体", "parties", "甲方", "乙方"],
            "A2": ["标的", "subject matter", "scope", "范围"],
            "A3": ["期限", "term", "续期", "renewal"],
            "A4": ["金额", "价格", "price", "payment", "付款"],
            "B1": ["违约", "default", "breach", "责任"],
            "B2": ["保密", "confidential", "保密条款"],
            "B3": ["知识产权", "intellectual property"],
            "B4": ["不可抗力", "force majeure"],
            "B5": ["竞业", "non-compete", "竞业限制"],
            "C1": ["争议", "dispute", "仲裁", "诉讼"],
            "C2": ["终止", "termination", "解除"],
            "C3": ["转让", "assignment", "分包"],
        },
        "simple_rule_ids": {"A5", "C4", "C5"},
        "complex_rule_ids": {
            "A1",
            "A2",
            "A3",
            "A4",
            "B1",
            "B2",
            "B3",
            "B4",
            "B5",
            "C1",
            "C2",
            "C3",
        }
}
