"""Configuration for employment document type."""

from app.agents.rules.employment_rules import EMPLOYMENT_RULES

CONFIG = {
    "name": "劳动合同",
    "report_title": "AI 劳动合同审查报告",
    "chapter_keywords": [
        "合同期限",
        "劳动期限",
        "contract term",
        "试用期",
        "probation",
        "工作内容",
        "工作岗位",
        "job description",
        "职责",
        "工作地点",
        "work location",
        "劳动报酬",
        "工资",
        "薪酬",
        "salary",
        "compensation",
        "工作时间",
        "工时",
        "working hours",
        "加班",
        "社会保险",
        "五险一金",
        "福利",
        "保密",
        "confidential",
        "竞业限制",
        "non-compete",
        "培训",
        "服务期",
        "training",
        "知识产权",
        "intellectual property",
        "合同解除",
        "termination",
        "解除",
        "争议",
        "dispute",
        "仲裁",
        "其他",
        "miscellaneous",
        "签署",
        "signature",
    ],
    "entity_patterns": [
        r"(?:用人单位|甲方|乙方|雇主|Employee|Employer)[：:\s]*([^\n,，。；;]+?(?:公司|企业|集团|个人|Co\.|Ltd\.|LLP|Inc\.|Corp\.))",
    ],
    "fact_tool_schema": {
        "type": "object",
        "properties": {
            "employer_name": {"type": "string", "description": "用人单位名称"},
            "employee_name": {"type": "string", "description": "员工姓名"},
            "position": {"type": "string", "description": "工作岗位"},
            "contract_type": {
                "type": "string",
                "description": "合同类型（固定期限/无固定期限）",
            },
            "contract_term": {"type": "string", "description": "合同期限"},
            "probation_period": {"type": "string", "description": "试用期"},
            "salary": {"type": "string", "description": "工资标准"},
            "work_location": {"type": "string", "description": "工作地点"},
            "working_hours": {"type": "string", "description": "工时制度"},
            "non_compete_included": {"type": "boolean", "description": "是否包含竞业限制"},
            "non_compete_compensation": {"type": "string", "description": "竞业限制补偿金"},
            "social_insurance": {"type": "boolean", "description": "是否约定缴纳社保"},
        },
        "required": [],
    },
    "risk_rules": EMPLOYMENT_RULES,
    "rule_keyword_map": {
        "A1": ["合同期限", "contract term", "试用期", "probation"],
        "A2": ["工作内容", "job description", "工作岗位", "工作地点"],
        "A3": ["工资", "salary", "劳动报酬", "薪酬"],
        "A4": ["工作时间", "working hours", "加班", "工时"],
        "A5": ["社保", "social insurance", "五险一金", "福利"],
        "B1": ["竞业限制", "non-compete", "竞业"],
        "B2": ["保密", "confidential", "保密条款"],
        "B3": ["培训", "training", "服务期"],
        "B4": ["知识产权", "intellectual property"],
        "C1": ["解除", "termination", "终止"],
        "C2": ["争议", "dispute", "仲裁"],
        "C3": ["违约", "breach", "违约金"],
    },
    "simple_rule_ids": {"A5", "B5", "C3"},
    "complex_rule_ids": {"A1", "A2", "A3", "A4", "B1", "B2", "B3", "B4", "C1", "C2"},
}
