"""Configuration for equity_investment document type."""

from app.agents.rules.equity_investment_rules import EQUITY_INVESTMENT_RULES

CONFIG = {
        "name": "股权投资协议",
        "report_title": "AI 股权投资协议审查报告",
        "chapter_keywords": [
            "定义",
            "definitions",
            "投资",
            "investment",
            "估值",
            "valuation",
            "投资金额",
            "交割",
            "closing",
            "先决条件",
            "反稀释",
            "anti-dilution",
            "优先权",
            "priority",
            "优先认购",
            "优先购买",
            "共同出售",
            "回购",
            "redemption",
            "buyback",
            "陈述与保证",
            "representations",
            "warranties",
            "竞业",
            "non-compete",
            "违约",
            "default",
            "终止",
            "termination",
            "争议解决",
            "dispute resolution",
            "其他",
            "miscellaneous",
            "签署",
            "signature",
        ],
        "entity_patterns": [
            r"(?:投资方|目标公司|创始人|甲方|乙方|Investor|Target Company)[：:\s]*([^\n,，。；;]+?(?:公司|企业|集团|基金|合伙|Co\.|Ltd\.|LLP|Inc\.|Corp\.))",
        ],
        "fact_tool_schema": {
            "type": "object",
            "properties": {
                "investor_name": {"type": "string", "description": "投资方名称"},
                "target_company": {"type": "string", "description": "目标公司名称"},
                "investment_amount": {"type": "string", "description": "投资金额"},
                "pre_money_valuation": {"type": "string", "description": "投前估值"},
                "post_money_valuation": {"type": "string", "description": "投后估值"},
                "equity_percentage": {"type": "string", "description": "股权比例"},
                "closing_conditions": {"type": "string", "description": "交割条件"},
                "anti_dilution": {"type": "string", "description": "反稀释条款"},
                "board_seats": {"type": "string", "description": "董事会席位"},
            },
            "required": [],
        },
        "risk_rules": EQUITY_INVESTMENT_RULES,
        "rule_keyword_map": {
            "A1": ["投资方", "目标公司", "主体"],
            "A2": ["估值", "valuation", "投资金额"],
            "A3": ["交割", "closing", "先决条件"],
            "A4": ["资金用途", "use of proceeds"],
            "B1": ["反稀释", "anti-dilution"],
            "B2": ["优先权", "priority", "优先认购", "优先购买"],
            "B3": ["回购", "redemption", "buyback"],
            "B4": ["信息权", "information right", "检查权"],
            "C1": ["竞业", "non-compete", "创始人"],
            "C2": ["陈述", "representations", "保证"],
            "C3": ["争议", "dispute", "仲裁"],
        },
        "simple_rule_ids": {"A1", "C3"},
        "complex_rule_ids": {"A2", "A3", "A4", "B1", "B2", "B3", "B4", "C1", "C2"}
}
