"""Configuration for ip_license document type."""

from app.agents.rules.ip_license_rules import IP_LICENSE_RULES

CONFIG = {
    "name": "知识产权许可",
    "report_title": "AI 知识产权许可协议审查报告",
    "chapter_keywords": [
        "定义",
        "definitions",
        "许可",
        "license",
        "许可范围",
        "scope of license",
        "许可方式",
        "许可费",
        "royalty",
        "许可使用费",
        "许可期限",
        "license term",
        "知识产权",
        "intellectual property",
        "专利",
        "商标",
        "著作权",
        "保密",
        "confidential",
        "改进",
        "improvement",
        "违约",
        "default",
        "breach",
        "终止",
        "termination",
        "争议解决",
        "dispute resolution",
        "其他",
        "miscellaneous",
        "签署",
        "signature",
    ],
    "entity_patterns": [
        r"(?:许可方|被许可方|甲方|乙方|Licensor|Licensee)[：:\s]*([^\n,，。；;]+?(?:公司|企业|集团|个人|Co\.|Ltd\.|LLP|Inc\.|Corp\.))",
    ],
    "fact_tool_schema": {
        "type": "object",
        "properties": {
            "licensor_name": {"type": "string", "description": "许可方名称"},
            "licensee_name": {"type": "string", "description": "被许可方名称"},
            "ip_type": {"type": "string", "description": "知识产权类型"},
            "ip_number": {"type": "string", "description": "权利证书编号"},
            "license_type": {"type": "string", "description": "许可方式（独占/排他/普通）"},
            "license_scope": {"type": "string", "description": "许可范围"},
            "license_term": {"type": "string", "description": "许可期限"},
            "royalty_amount": {"type": "string", "description": "许可费"},
        },
        "required": [],
    },
    "risk_rules": IP_LICENSE_RULES,
    "rule_keyword_map": {
        "A1": ["许可方", "被许可方", "主体"],
        "A2": ["知识产权", "IP", "专利", "商标", "著作权"],
        "A3": ["许可范围", "scope", "许可方式", "独占", "排他"],
        "A4": ["期限", "term", "许可期限"],
        "B1": ["许可费", "royalty", "费用"],
        "B2": ["保护", "protection", "侵权"],
        "B3": ["改进", "improvement", "回授"],
        "B4": ["保密", "confidential"],
        "C1": ["违约", "default", "终止"],
        "C2": ["侵权", "infringement", "担保"],
        "C3": ["争议", "dispute", "仲裁"],
    },
    "simple_rule_ids": {"A1", "C3"},
    "complex_rule_ids": {"A2", "A3", "A4", "B1", "B2", "B3", "B4", "C1", "C2"},
}
