"""Configuration for lease document type."""

from app.agents.rules.lease_rules import LEASE_RULES

CONFIG = {
        "name": "租赁合同",
        "report_title": "AI 租赁合同审查报告",
        "chapter_keywords": [
            "定义",
            "definitions",
            "租赁物",
            "premises",
            "租赁标的",
            "租金",
            "rent",
            "lease payment",
            "租赁期限",
            "lease term",
            "term",
            "维修",
            "maintenance",
            "repair",
            "转租",
            "sublease",
            "subletting",
            "装修",
            "renovation",
            "improvement",
            "违约",
            "default",
            "breach",
            "合同终止",
            "termination",
            "解除",
            "争议解决",
            "dispute resolution",
            "其他",
            "miscellaneous",
            "签署",
            "signature",
        ],
        "entity_patterns": [
            r"(?:出租方|承租方|甲方|乙方|房东|租户|Landlord|Tenant)[：:\s]*([^\n,，。；;]+?(?:公司|企业|集团|个人|Co\.|Ltd\.|LLP|Inc\.|Corp\.))",
        ],
        "fact_tool_schema": {
            "type": "object",
            "properties": {
                "landlord_name": {"type": "string", "description": "出租方名称"},
                "tenant_name": {"type": "string", "description": "承租方名称"},
                "premises_address": {"type": "string", "description": "租赁物地址"},
                "premises_area": {"type": "string", "description": "租赁面积"},
                "lease_purpose": {"type": "string", "description": "租赁用途"},
                "lease_term": {"type": "string", "description": "租赁期限"},
                "rent_amount": {"type": "string", "description": "租金金额"},
                "payment_cycle": {"type": "string", "description": "支付周期"},
                "deposit_amount": {"type": "string", "description": "押金金额"},
                "renewal_terms": {"type": "string", "description": "续租条件"},
            },
            "required": [],
        },
        "risk_rules": LEASE_RULES,
        "rule_keyword_map": {
            "A1": ["租赁物", "premises", "地址", "面积"],
            "A2": ["期限", "term", "租期", "续租"],
            "A3": ["租金", "rent", "付款", "押金"],
            "A4": ["主体", "parties", "出租方", "承租方"],
            "B1": ["维修", "maintenance", "保养"],
            "B2": ["转租", "sublease", "分租"],
            "B3": ["装修", "renovation", "改造"],
            "B4": ["违约", "default", "breach"],
            "C1": ["登记", "备案", "registration"],
            "C2": ["终止", "termination", "交接"],
            "C3": ["争议", "dispute", "仲裁"],
        },
        "simple_rule_ids": {"C1", "C3"},
        "complex_rule_ids": {"A1", "A2", "A3", "A4", "B1", "B2", "B3", "B4", "C2"}
}
