"""Configuration for loan document type."""

from app.agents.rules.loan_rules import LOAN_RULES

CONFIG = {
        "name": "借款合同",
        "report_title": "AI 借款合同审查报告",
        "chapter_keywords": [
            "定义",
            "definitions",
            "借款",
            "loan",
            "借款金额",
            "loan amount",
            "principal",
            "利率",
            "interest rate",
            "利息",
            "借款期限",
            "loan term",
            "maturity",
            "还款",
            "repayment",
            "偿还",
            "担保",
            "guarantee",
            "security",
            "抵押",
            "质押",
            "违约",
            "default",
            "逾期",
            "合同终止",
            "termination",
            "争议解决",
            "dispute resolution",
            "其他",
            "miscellaneous",
            "签署",
            "signature",
        ],
        "entity_patterns": [
            r"(?:出借人|借款人|甲方|乙方|贷款人|Lender|Borrower)[：:\s]*([^\n,，。；;]+?(?:公司|企业|集团|银行|个人|Co\.|Ltd\.|LLP|Inc\.|Corp\.))",
        ],
        "fact_tool_schema": {
            "type": "object",
            "properties": {
                "lender_name": {"type": "string", "description": "出借人名称"},
                "borrower_name": {"type": "string", "description": "借款人名称"},
                "loan_amount": {"type": "string", "description": "借款金额"},
                "interest_rate": {"type": "string", "description": "利率"},
                "loan_term": {"type": "string", "description": "借款期限"},
                "repayment_method": {"type": "string", "description": "还款方式"},
                "guarantee_type": {"type": "string", "description": "担保方式"},
                "loan_purpose": {"type": "string", "description": "借款用途"},
                "penalty_rate": {"type": "string", "description": "罚息利率"},
            },
            "required": [],
        },
        "risk_rules": LOAN_RULES,
        "rule_keyword_map": {
            "A1": ["主体", "parties", "出借人", "借款人"],
            "A2": ["金额", "amount", "借款金额"],
            "A3": ["期限", "term", "借款期限"],
            "A4": ["利率", "interest", "利息"],
            "B1": ["担保", "guarantee", "抵押", "质押"],
            "B2": ["还款", "repayment", "偿还"],
            "B3": ["违约", "default", "罚息"],
            "B4": ["用途", "purpose", "借款用途"],
            "C1": ["生效", "effectiveness", "交付"],
            "C2": ["争议", "dispute", "仲裁"],
            "C3": ["税费", "tax", "印花税"],
        },
        "simple_rule_ids": {"A1", "C2", "C3"},
        "complex_rule_ids": {"A2", "A3", "A4", "B1", "B2", "B3", "B4", "C1"}
}
