"""Configuration for marital_property document type."""

from app.agents.rules.marital_property_rules import MARITAL_PROPERTY_RULES

CONFIG = {
    "name": "婚姻财产协议",
    "report_title": "AI 婚姻财产协议审查报告",
    "chapter_keywords": [
        "双方信息",
        "婚姻状况",
        "财产范围",
        "财产清单",
        "房产",
        "不动产",
        "存款",
        "投资",
        "股权",
        "车辆",
        "动产",
        "债务",
        "债权",
        "收入",
        "工资",
        "赠与",
        "继承",
        "补偿",
        "帮助",
        "变更",
        "撤销",
        "生效",
        "公证",
        "争议",
        "其他",
        "签署",
    ],
    "entity_patterns": [
        r"(?:男方|女方|丈夫|妻子|甲方|乙方|Husband|Wife)[：:\s]*([^\n,，。；;]+)",
    ],
    "fact_tool_schema": {
        "type": "object",
        "properties": {
            "husband_name": {"type": "string", "description": "男方姓名"},
            "wife_name": {"type": "string", "description": "女方姓名"},
            "marriage_date": {"type": "string", "description": "结婚日期"},
            "property_scope": {"type": "string", "description": "财产范围"},
            "real_estate": {"type": "string", "description": "房产信息"},
            "vehicles": {"type": "string", "description": "车辆信息"},
            "investments": {"type": "string", "description": "投资信息"},
            "debt_arrangement": {"type": "string", "description": "债务安排"},
            "notarized": {"type": "boolean", "description": "是否公证"},
        },
        "required": [],
    },
    "risk_rules": MARITAL_PROPERTY_RULES,
    "rule_keyword_map": {
        "A1": ["身份", "姓名", "婚姻"],
        "A2": ["财产范围", "财产清单", "房产", "存款"],
        "A3": ["归属", "各自所有", "共同所有"],
        "B1": ["债务", "共同债务", "连带"],
        "B2": ["收入", "工资", "开支"],
        "B3": ["赠与", "继承"],
        "B4": ["补偿", "帮助"],
        "C1": ["变更", "撤销"],
        "C2": ["生效", "公证"],
        "C3": ["争议"],
    },
    "simple_rule_ids": {"A1", "C3"},
    "complex_rule_ids": {"A2", "A3", "B1", "B2", "B3", "B4", "C1", "C2"},
}
