"""Configuration for nda document type."""

from app.agents.rules.nda_rules import NDA_RULES

CONFIG = {
        "name": "保密协议 (NDA)",
        "report_title": "AI NDA 合同审查报告",
        "chapter_keywords": [
            "定义",
            "definitions",
            "保密信息",
            "confidential information",
            "保密义务",
            "confidentiality obligation",
            "使用限制",
            "use restriction",
            "purpose",
            "期限",
            "term",
            "duration",
            "有效期",
            "返还",
            "return",
            "销毁",
            "destruction",
            "违约",
            "breach",
            "default",
            "责任",
            "救济",
            "remedy",
            "禁令",
            "injunction",
            "争议解决",
            "dispute resolution",
            "仲裁",
            "诉讼",
            "适用法律",
            "governing law",
            "转让",
            "assignment",
            "通知",
            "notice",
            "其他",
            "miscellaneous",
            "签署",
            "signature",
            "execution",
        ],
        "entity_patterns": [
            r"(?:甲方|乙方|丙方|披露方|接收方|Disclosing Party|Receiving Party)[：:\s]*([^\n,，。；;]+?(?:公司|企业|集团|Co\.|Ltd\.|LLP|Inc\.|Corp\.))",
        ],
        "fact_tool_schema": {
            "type": "object",
            "properties": {
                "disclosing_party": {"type": "string", "description": "披露方名称"},
                "receiving_party": {"type": "string", "description": "接收方名称"},
                "confidential_info_scope": {"type": "string", "description": "保密信息范围"},
                "confidentiality_period": {"type": "string", "description": "保密期限"},
                "purpose": {"type": "string", "description": "使用目的"},
                "governing_law": {"type": "string", "description": "适用法律"},
                "dispute_resolution": {"type": "string", "description": "争议解决方式"},
                "non_compete_included": {"type": "boolean", "description": "是否包含竞业限制条款"},
                "non_solicit_included": {"type": "boolean", "description": "是否包含非招揽条款"},
                "remedy_provisions": {"type": "string", "description": "救济措施"},
            },
            "required": [],
        },
        "risk_rules": NDA_RULES,
        "rule_keyword_map": {
            "A1": ["保密信息", "confidential information", "定义"],
            "A2": ["保密义务", "confidentiality obligation", "义务范围"],
            "A3": ["期限", "term", "duration", "保密期限"],
            "A4": ["关联方", "affiliate", "子公司"],
            "B1": ["使用限制", "use restriction", "目的", "purpose"],
            "B2": ["披露", "disclosure", "第三方"],
            "B3": ["返还", "return", "销毁", "destruction"],
            "B4": ["知识产权", "intellectual property"],
            "B5": ["竞业", "non-compete", "非招揽", "non-solicit"],
            "C1": ["违约", "breach", "救济", "remedy"],
            "C2": ["争议", "dispute", "仲裁", "诉讼"],
        },
        "simple_rule_ids": {"A4", "C3"},
        "complex_rule_ids": {"A1", "A2", "A3", "B1", "B2", "B3", "B4", "B5", "C1", "C2"}
}
