"""Configuration for sales document type."""

from app.agents.rules.sales_rules import SALES_RULES

CONFIG = {
    "name": "买卖合同",
    "report_title": "AI 买卖合同审查报告",
    "chapter_keywords": [
        "定义",
        "definitions",
        "标的物",
        "subject matter",
        "价款",
        "价格",
        "price",
        "payment",
        "交付",
        "delivery",
        "交货",
        "验收",
        "acceptance",
        "inspection",
        "质量",
        "quality",
        "warranty",
        "违约",
        "default",
        "breach",
        "包装",
        "packaging",
        "运输",
        "合同终止",
        "termination",
        "争议解决",
        "dispute resolution",
        "其他",
        "miscellaneous",
        "签署",
        "signature",
    ],
    "entity_patterns": [
        r"(?:买方|卖方|甲方|乙方|采购方|供应方|Buyer|Seller)[：:\s]*([^\n,，。；;]+?(?:公司|企业|集团|Co\.|Ltd\.|LLP|Inc\.|Corp\.))",
    ],
    "fact_tool_schema": {
        "type": "object",
        "properties": {
            "buyer_name": {"type": "string", "description": "买方名称"},
            "seller_name": {"type": "string", "description": "卖方名称"},
            "product_name": {"type": "string", "description": "标的物名称"},
            "product_spec": {"type": "string", "description": "标的物规格"},
            "quantity": {"type": "string", "description": "数量"},
            "unit_price": {"type": "string", "description": "单价"},
            "total_price": {"type": "string", "description": "总价"},
            "delivery_date": {"type": "string", "description": "交付日期"},
            "delivery_location": {"type": "string", "description": "交付地点"},
            "payment_terms": {"type": "string", "description": "付款条件"},
        },
        "required": [],
    },
    "risk_rules": SALES_RULES,
    "rule_keyword_map": {
        "A1": ["主体", "parties", "买方", "卖方"],
        "A2": ["标的物", "subject matter", "规格", "数量"],
        "A3": ["价格", "price", "付款", "金额"],
        "A4": ["交付", "delivery", "验收", "运输"],
        "B1": ["质量", "quality", "售后", "保修"],
        "B2": ["违约", "default", "breach"],
        "B3": ["知识产权", "IP"],
        "B4": ["保密", "confidential"],
        "C1": ["不可抗力", "force majeure"],
        "C2": ["终止", "termination", "解除"],
        "C3": ["争议", "dispute", "仲裁"],
    },
    "simple_rule_ids": {"A1", "B4", "C3"},
    "complex_rule_ids": {"A2", "A3", "A4", "B1", "B2", "B3", "C1", "C2"},
}
