"""Configuration for service document type."""

from app.agents.rules.service_rules import SERVICE_RULES

CONFIG = {
    "name": "服务合同",
    "report_title": "AI 服务合同审查报告",
    "chapter_keywords": [
        "定义",
        "definitions",
        "服务内容",
        "scope of services",
        "服务期限",
        "service term",
        "服务费用",
        "service fee",
        "报酬",
        "服务质量",
        "service quality",
        "KPI",
        "SLA",
        "人员",
        "personnel",
        "团队",
        "保密",
        "confidential",
        "知识产权",
        "intellectual property",
        "违约",
        "default",
        "breach",
        "合同终止",
        "termination",
        "争议解决",
        "dispute resolution",
        "其他",
        "miscellaneous",
        "签署",
        "signature",
    ],
    "entity_patterns": [
        r"(?:委托方|受托方|甲方|乙方|服务方|Client|Service Provider)[：:\s]*([^\n,，。；;]+?(?:公司|企业|集团|Co\.|Ltd\.|LLP|Inc\.|Corp\.))",
    ],
    "fact_tool_schema": {
        "type": "object",
        "properties": {
            "client_name": {"type": "string", "description": "委托方名称"},
            "provider_name": {"type": "string", "description": "受托方名称"},
            "service_scope": {"type": "string", "description": "服务内容"},
            "service_term": {"type": "string", "description": "服务期限"},
            "service_fee": {"type": "string", "description": "服务费用"},
            "payment_method": {"type": "string", "description": "付款方式"},
            "kpi_sla": {"type": "string", "description": "服务质量标准"},
            "key_personnel": {"type": "string", "description": "核心人员"},
        },
        "required": [],
    },
    "risk_rules": SERVICE_RULES,
    "rule_keyword_map": {
        "A1": ["主体", "parties", "委托方", "受托方"],
        "A2": ["服务内容", "scope", "范围"],
        "A3": ["期限", "term", "服务期限"],
        "A4": ["费用", "fee", "报酬", "付款"],
        "B1": ["质量", "quality", "KPI", "SLA"],
        "B2": ["人员", "personnel", "团队"],
        "B3": ["保密", "confidential", "数据"],
        "B4": ["知识产权", "IP"],
        "C1": ["违约", "default", "breach"],
        "C2": ["终止", "termination", "交接"],
        "C3": ["争议", "dispute", "仲裁"],
    },
    "simple_rule_ids": {"A1", "C3"},
    "complex_rule_ids": {"A2", "A3", "A4", "B1", "B2", "B3", "B4", "C1", "C2"},
}
