"""Configuration for will_estate document type."""

from app.agents.rules.will_estate_rules import WILL_ESTATE_RULES

CONFIG = {
        "name": "遗嘱/继承",
        "report_title": "AI 遗嘱/继承文件审查报告",
        "chapter_keywords": [
            "立遗嘱人",
            "遗嘱人",
            "遗产",
            "财产",
            "继承人",
            "受遗赠人",
            "房产",
            "不动产",
            "存款",
            "投资",
            "遗嘱形式",
            "自书遗嘱",
            "代书遗嘱",
            "公证遗嘱",
            "见证人",
            "遗嘱执行",
            "执行人",
            "债务",
            "清偿",
            "变更",
            "撤销",
            "争议",
            "其他",
            "签署",
        ],
        "entity_patterns": [
            r"(?:立遗嘱人|遗嘱人|继承人|受遗赠人|见证人|Testator|Beneficiary)[：:\s]*([^\n,，。；;]+)",
        ],
        "fact_tool_schema": {
            "type": "object",
            "properties": {
                "testator_name": {"type": "string", "description": "立遗嘱人姓名"},
                "testator_id": {"type": "string", "description": "立遗嘱人身份证号"},
                "will_type": {"type": "string", "description": "遗嘱形式"},
                "estate_scope": {"type": "string", "description": "遗产范围"},
                "beneficiaries": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "继承人/受遗赠人列表",
                },
                "witnesses": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "见证人列表",
                },
                "executor": {"type": "string", "description": "遗嘱执行人"},
                "special_conditions": {"type": "string", "description": "特殊条件或负担"},
            },
            "required": [],
        },
        "risk_rules": WILL_ESTATE_RULES,
        "rule_keyword_map": {
            "A1": ["立遗嘱人", "身份", "行为能力"],
            "A2": ["遗产", "财产范围", "财产清单"],
            "A3": ["继承人", "受遗赠人", "必留份"],
            "B1": ["遗嘱形式", "自书", "代书", "打印", "公证"],
            "B2": ["见证人", "资格"],
            "B3": ["合法性", "公序良俗"],
            "C1": ["变更", "撤销", "多份遗嘱"],
            "C2": ["遗嘱执行", "执行人"],
            "C3": ["债务", "清偿"],
        },
        "simple_rule_ids": {"A1", "C2", "C3"},
        "complex_rule_ids": {"A2", "A3", "B1", "B2", "B3", "C1"},
}
